ALTER TABLE teos.users
ADD created_by BIGINT UNSIGNED NOT NULL;
ALTER TABLE teos.users
ADD created_at TIMESTAMP NOT NULL;
ALTER TABLE teos.users
ADD updated_by BIGINT UNSIGNED NOT NULL;
ALTER TABLE teos.users
ADD updated_at TIMESTAMP NOT NULL;
ALTER TABLE teos.users
ADD deleted_by BIGINT UNSIGNED NULL;
ALTER TABLE teos.users
ADD deleted_at TIMESTAMP NULL;