ALTER TABLE teos.users
ADD createdBy BIGINT UNSIGNED NOT NULL;
ALTER TABLE teos.users
ADD createdAt TIMESTAMP NOT NULL;
ALTER TABLE teos.users
ADD updatedBy BIGINT UNSIGNED NOT NULL;
ALTER TABLE teos.users
ADD updatedAt TIMESTAMP NULL;
ALTER TABLE teos.users
ADD deletedBy BIGINT UNSIGNED NULL;
ALTER TABLE teos.users
ADD deletedAt TIMESTAMP NULL;