db.app_configurations.insertMany(
    [
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_NAME",
            "type":"string",
            "valueInt":null,
            "valueString":"teos_auth",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_EXPIRE",
            "type":"int",
            "valueInt":900,
            "valueString":null,
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_DOMAIN",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_HTTP_ONLY",
            "type":"bool",
            "valueInt":null,
            "valueString":null,
            "valueFloat":null,
            "valueBool": true,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_SECURE",
            "type":"bool",
            "valueInt":null,
            "valueString":null,
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a14'),
            "name": "Chave de autenticação",
            "description": "Chave de autenticação para o serviço Apps",
            "key": "APP_AUTH_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"b91e2e7a-3a9e-4f24-8b1c-bbfb84b7673e",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "Chave de autenticação",
            "description": "Chave de autenticação para o serviço Auth",
            "key": "APP_AUTH_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"293d404c-8cc0-4d2c-9c36-a0e0b02b5c37",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a16'),
            "name": "Chave de autenticação",
            "description": "Chave de autenticação para o serviço Users",
            "key": "APP_AUTH_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"6743ddf6-df3a-4dbe-bcbd-181ab5ddecc2",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a17'),
            "name": "Chave de autenticação",
            "description": "Chave de autenticação para o serviço Hists",
            "key": "APP_AUTH_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"1a55c43e-b729-424c-a385-449f69d92c91",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "SECRET_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"bwfeb778(*!$dag#Fahjd",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "SECRET_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"bwfeb778(*!$dag#Fahjd",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a14'),
            "name": "",
            "description": "",
            "key": "NET_DNS",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a14'),
            "name": "",
            "description": "",
            "key": "NET_PORT",
            "type":"string",
            "valueInt":8083,
            "valueString":null,
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "NET_DNS",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "NET_PORT",
            "type":"string",
            "valueInt":8080,
            "valueString":null,
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a16'),
            "name": "",
            "description": "",
            "key": "NET_DNS",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a16'),
            "name": "",
            "description": "",
            "key": "NET_PORT",
            "type":"string",
            "valueInt":8082,
            "valueString":null,
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a17'),
            "name": "",
            "description": "",
            "key": "NET_DNS",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a17'),
            "name": "",
            "description": "",
            "key": "NET_PORT",
            "type":"string",
            "valueInt":8081,
            "valueString":null,
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db History Address",
            "description": "Redis server address for history data",
            "key": "REDIS_DB_HIST_ADDRESS",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db History Passwd",
            "description": "Redis password for history data",
            "key": "REDIS_DB_HIST_PASSWORD",
            "type":"string",
            "valueInt":null,
            "valueString":"",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db History Db",
            "description": "Redis database number for history data",
            "key": "REDIS_DB_HIST_DATABASE",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Log Address",
            "description": "Redis server address for log data",
            "key": "REDIS_DB_LOG_ADDRESS",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Log Passwd",
            "description": "Redis password for log data",
            "key": "REDIS_DB_LOG_PASSWORD",
            "type":"string",
            "valueInt":null,
            "valueString":"",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Log Db",
            "description": "Redis database number for log data",
            "key": "REDIS_DB_LOG_DATABASE",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Session Address",
            "description": "Redis server address for session data",
            "key": "REDIS_DB_SESSION_ADDRESS",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Session Passwd",
            "description": "Redis password for session data",
            "key": "REDIS_DB_SESSION_PASSWORD",
            "type":"string",
            "valueInt":null,
            "valueString":"",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Session Db",
            "description": "Redis database number for session data",
            "key": "REDIS_DB_SESSION_DATABASE",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Permissions Address",
            "description": "Redis server address for user permissions data",
            "key": "REDIS_DB_PERMISSIONS_ADDRESS",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Permissions Passwd",
            "description": "Redis password for user permissions data",
            "key": "REDIS_DB_PERMISSIONS_PASSWORD",
            "type":"string",
            "valueInt":null,
            "valueString":"",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": null,
            "name": "Db Session Db",
            "description": "Redis database number for user permissions data",
            "key": "REDIS_DB_PERMISSIONS_DATABASE",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
    ]
)


db.app_configurations.insertMany([
    {
        "appAppId": null,
        "name": "Db Session Address",
        "description": "Redis server address for session data",
        "key": "REDIS_DB_SESSION_ADDRESS",
        "type":"string",
        "valueInt":null,
        "valueString":"localhost",
        "valueFloat":null,
        "valueBool": false,
        "createedBy":ObjectId('666758b475cf5396aea26a13'),
        "createdAt": new Date(),
        "updatedBy":ObjectId('666758b475cf5396aea26a13'),
        "updatedAt": new Date(),
        "deletedBy":null,
        "deletedAt": null,
    },
    {
        "appAppId": null,
        "name": "Db Session Passwd",
        "description": "Redis password for session data",
        "key": "REDIS_DB_SESSION_PASSWORD",
        "type":"string",
        "valueInt":null,
        "valueString":"",
        "valueFloat":null,
        "valueBool": false,
        "createedBy":ObjectId('666758b475cf5396aea26a13'),
        "createdAt": new Date(),
        "updatedBy":ObjectId('666758b475cf5396aea26a13'),
        "updatedAt": new Date(),
        "deletedBy":null,
        "deletedAt": null,
    },
    {
        "appAppId": null,
        "name": "Db Session Db",
        "description": "Redis database number for session data",
        "key": "REDIS_DB_SESSION_DATABASE",
        "type":"string",
        "valueInt":null,
        "valueString":"localhost",
        "valueFloat":null,
        "valueBool": false,
        "createedBy":ObjectId('666758b475cf5396aea26a13'),
        "createdAt": new Date(),
        "updatedBy":ObjectId('666758b475cf5396aea26a13'),
        "updatedAt": new Date(),
        "deletedBy":null,
        "deletedAt": null,
    },
    {
        "appAppId": null,
        "name": "Db Permissions Address",
        "description": "Redis server address for user permissions data",
        "key": "REDIS_DB_PERMISSIONS_ADDRESS",
        "type":"string",
        "valueInt":null,
        "valueString":"localhost",
        "valueFloat":null,
        "valueBool": false,
        "createedBy":ObjectId('666758b475cf5396aea26a13'),
        "createdAt": new Date(),
        "updatedBy":ObjectId('666758b475cf5396aea26a13'),
        "updatedAt": new Date(),
        "deletedBy":null,
        "deletedAt": null,
    },
    {
        "appAppId": null,
        "name": "Db Permissions Passwd",
        "description": "Redis password for user permissions data",
        "key": "REDIS_DB_PERMISSIONS_PASSWORD",
        "type":"string",
        "valueInt":null,
        "valueString":"",
        "valueFloat":null,
        "valueBool": false,
        "createedBy":ObjectId('666758b475cf5396aea26a13'),
        "createdAt": new Date(),
        "updatedBy":ObjectId('666758b475cf5396aea26a13'),
        "updatedAt": new Date(),
        "deletedBy":null,
        "deletedAt": null,
    },
    {
        "appAppId": null,
        "name": "Db Session Db",
        "description": "Redis database number for user permissions data",
        "key": "REDIS_DB_PERMISSIONS_DATABASE",
        "type":"string",
        "valueInt":null,
        "valueString":"localhost",
        "valueFloat":null,
        "valueBool": false,
        "createedBy":ObjectId('666758b475cf5396aea26a13'),
        "createdAt": new Date(),
        "updatedBy":ObjectId('666758b475cf5396aea26a13'),
        "updatedAt": new Date(),
        "deletedBy":null,
        "deletedAt": null,
    },
]);