db.app_configurations.insertMany(
    [
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_NAME",
            "type":"string",
            "valueInt":null,
            "valueString":"teos_auth",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_EXPIRE",
            "type":"int",
            "valueInt":900,
            "valueString":null,
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_DOMAIN",
            "type":"string",
            "valueInt":null,
            "valueString":"localhost",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_HTTP_ONLY",
            "type":"bool",
            "valueInt":null,
            "valueString":null,
            "valueFloat":null,
            "valueBool": true,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "",
            "description": "",
            "key": "COOKIE_SECURE",
            "type":"bool",
            "valueInt":null,
            "valueString":null,
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a14'),
            "name": "Chave de autenticação",
            "description": "Chave de autenticação para o serviço Apps",
            "key": "APP_AUTH_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"b91e2e7a-3a9e-4f24-8b1c-bbfb84b7673e",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a15'),
            "name": "Chave de autenticação",
            "description": "Chave de autenticação para o serviço Auth",
            "key": "APP_AUTH_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"293d404c-8cc0-4d2c-9c36-a0e0b02b5c37",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a16'),
            "name": "Chave de autenticação",
            "description": "Chave de autenticação para o serviço Users",
            "key": "APP_AUTH_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"6743ddf6-df3a-4dbe-bcbd-181ab5ddecc2",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
        {
            "appAppId": ObjectId('66675b3575cf5396aea26a17'),
            "name": "Chave de autenticação",
            "description": "Chave de autenticação para o serviço Hists",
            "key": "APP_AUTH_KEY",
            "type":"string",
            "valueInt":null,
            "valueString":"1a55c43e-b729-424c-a385-449f69d92c91",
            "valueFloat":null,
            "valueBool": false,
            "createedBy":ObjectId('666758b475cf5396aea26a13'),
            "createdAt": new Date(),
            "updatedBy":ObjectId('666758b475cf5396aea26a13'),
            "updatedAt": new Date(),
            "deletedBy":null,
            "deletedAt": null,
        },
    ]
)