ALTER TABLE `table` ADD COLUMN `created_by` INT UNSIGNED NOT NULL;
ALTER TABLE `table` ADD COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp();
ALTER TABLE `table` ADD COLUMN `updated_by` INT UNSIGNED NOT NULL;
ALTER TABLE `table` ADD COLUMN `updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp();
ALTER TABLE `table` ADD COLUMN `deleted_by` INT UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `table` ADD COLUMN `deleted_at` TIMESTAMP NULL DEFAULT NULL;

